### ISSUE TITLE
Dockerization of Discord Bot

### ISSUE THREAD

**Issue by santa-17** [LazyBuds/tommy-discord#1]
Currently the whole process of deployement is manual , that is we create a manual instance of EC2 in AWS and proceed to install all the dependencies manually and deploying the bot.

**The main tasks would be:**
1) Creating a `requirements.txt` file for automated python dependencies installation.
2) creating a `dockerfile` to install all dependencies and run the project.

**Comment by nirgude** [comment]
Hi , can you assign this issue to me?
I would also recommend to use CI/CD actions to automate deployment to AWS

**Comment by santa-17** [comment]
Hi @nirgude go ahead, I would love to have a pipeline setup after you are done with the docker and let me know if you have any ideas about the pipeline. Cheers!

**Comment by nirgude** [comment]
Hi, can you please assign this issue @nidhip0108

**Comment by santa-17** [comment]
sure! can you also let me know about the ci/cd?

**Comment by nidhip0108** [comment]
yes! I would like to work on it

**Comment by santa-17** [comment]
sure! can you also update me about ci/cd! would love to know a bit more.. If you have any references to articles/docs I can use please do mention!

**Comment by nidhip0108** [comment]
hey, I added a pr for the task can you please review it ? #2

**Comment by nidhip0108** [comment]
I found this great article by Azzan Amin on medium which gives detail about how to use 

- Github actions 
- AWS codedeploy
- AWS EC2 

Honestly speaking its really a pain to setup but its worth the effort to set up the pipeline
https://medium.com/thelorry-product-tech-data/amazon-ec2-deployment-complete-ci-cd-pipeline-using-github-actions-and-aws-codedeploy-8a477123ff7e

**Comment by santa-17** [comment]
> I found this great article by Azzan Amin on medium which gives detail about how to use
> 
> * Github actions
> * AWS codedeploy
> * AWS EC2
> 
> Honestly speaking its really a pain to setup but its worth the effort to set up the pipeline https://medium.com/thelorry-product-tech-data/amazon-ec2-deployment-complete-ci-cd-pipeline-using-github-actions-and-aws-codedeploy-8a477123ff7e

Thankyou! Definitely looks bad.. I'll try to set it up!
